### ISSUE TITLE
rules.html is broken badly

### ISSUE THREAD

**Issue by robske110** [JM-Lemmi/ical-relay#129] opened 2023-03-09 11:07 UTC
Attempting to delete a module on the edit page doesn't delete the module and instead overwrites other modules, corrupting data.
Probably worth creating a hot fix for.

**Comment by JM-Lemmi** [comment] 2023-04-19 16:39
Since #66 its completely broken

**Comment by JM-Lemmi** [comment] 2024-01-31 13:20
duplicate of #73

**Closed by JM-Lemmi** 2024-01-31 13:20 UTC
Labels: bug, modules
